clean_room:
  target:
    entity:
      integration: "sharkiq"
      domain: "vacuum"

  fields:
    rooms:
      required: true
      advanced: false
      example: "Kitchen"
      selector:
        select:
          options: []
          multiple: true
          custom_value: true
    clean_type:
      required: false
      advanced: false
      example: "dry"
      default: "dry"
      selector:
        select:
          options:
            - "dry"
            - "wet"
            - "matrix"
            - "spot"
    fan_speed:
      required: false
      advanced: false
      example: "Normal"
      selector:
        select:
          options:
            - "Eco"
            - "Normal"
            - "Max"

dashboard_yaml:
  target:
    entity:
      integration: "sharkiq"
      domain: "vacuum"
